### ISSUE TITLE
GitHub連携コンテンツ管理システム

### ISSUE THREAD

**Issue by Rindrics** [Rindrics/kanji-worksheet#13]
## 概要
GitHubからの特殊テーマコンテンツ取得・管理システムを実装します。

## タスク
- [ ] GitHub APIでのコンテンツ取得機能
- [ ] YAML/JSONパーサー実装
- [ ] コンテンツバリデーション機能
- [ ] 更新時の自動取り込み処理

## 受け入れ条件
- GitHub APIからのファイル取得
- YAML/JSON形式の解析
- 不正データのエラーハンドリング
- Webhookまたは定期更新

## ファイル形式例
```yaml
name: "般若心経"
description: "般若心経の漢字練習"
characters:
  - 般
  - 若
  - 心
  - 経
```
