### ISSUE TITLE
印刷最適化CSS・Media Query実装

### ISSUE THREAD

**Issue by Rindrics** [Rindrics/kanji-worksheet#9]
## 概要
印刷時の微調整とブラウザ印刷機能の最適化を行います。

## タスク
- [ ] Print Media Query実装（最小限）
- [ ] 不要要素の非表示設定（.no-printクラス）
- [ ] 改ページ制御（必要に応じて）
- [ ] 色・フォントの印刷最適化

## 受け入れ条件
- 印刷時に不要な要素が非表示
- 適切な改ページ制御
- インク節約を考慮した色設定
- 各ブラウザでの印刷結果確認

## CSS例
```css
@media print {
  .no-print { display: none !important; }
  @page { size: A4; margin: 15mm; }
}
```
